[package]
name = "rain-wasm"
version = "0.0.0"
authors = ["Jad Ghalayini <jad.ghalayini@hotmail.com>"]
edition = "2018"

[dependencies]
rain-ir = { git = "https://gitlab.com/rain-lang/rain-ir.git" }
parity-wasm = "^0.41"